
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/servlet?useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: ebid$2018
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis:
  mapper-locations:
  - classpath:com/lrw/dao/*.xml


server:
  port: 9090
    